language: c

before_install: 
  - sudo apt-get install -y swig
  - sudo apt-get install -y lua5.2
  - sudo apt-get install -y lua5.2-dev

script: ./configure && make

os:
  - linux

compiler:
  - clang
  - gcc
