language: c

before_install: 
  - sudo apt-get install -y swig
  - sudo apt-get install -y lua5.2
  - sudo apt-get install -y lua5.2-dev

install:
  - git clone https://github.com/ColumPaget/libUseful
  - pushd libUseful && ./configure && make && sudo make install && popd

script: ./configure && make

os:
  - linux

compiler:
  - clang
  - gcc
