language: c

before_install: 
  - sudo apt-get install -y swig
  - sudo apt-get install -y lua5.3
  - sudo apt-get install -y lua5.3-dev

script: ./configure && make

os:
  - linux

compiler:
  - clang
  - gcc
